name: Build and Deploy React App

on:
  push:
    branches:
      - prod  # Deploy only when pushing to prod branch

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies & build React
      - name: Install & Build React
        run: |
          cd $GITHUB_WORKSPACE               # Go to repo root
          npm ci                              # Clean install dependencies
          npm run build                        # Build the Vite React app (outputs to dist/)

      # 4️⃣ Deploy dist folder to your live site
      - name: Deploy to public_html
        run: |
          rsync -av --delete $GITHUB_WORKSPACE/dist/ /home/lsei9899/public_html/expenses-app/

      # 5️⃣ Optional: verify deployment
      - name: List deployed files
        run: |
          ls -l /home/lsei9899/public_html/expenses-app
