name: Deploy React App

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout React code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: |
          cd expenses-app   
          npm install
          npm run build

      - name: Copy build to subdomain folder
        run: rsync -av --delete ./expenses-app/build/ /home/lsei9899/public_html/expenses-app/
