name: Deploy React App

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout React code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: |
          cd $GITHUB_WORKSPACE   
          npm install
          npm run build

      - name: Show workspace
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -l
          find . -name build

      - name: Copy build to subdomain folder
        run: rsync -av --delete $GITHUB_WORKSPACE/build/ /home/lsei9899/public_html/expenses-app/
